"""Algorithmic template mapper forcing optimized runtime Big-O complexity execution."""
import logging
from src.agent.state import AgentWorkspaceState
from src.llm.client import inference_driver
from src.llm.templates import DSA_EXPERT_PROMPT

logger = logging.getLogger("backend.agent.nodes.dsa_expert")

async def dsa_expert_node(state: AgentWorkspaceState) -> AgentWorkspaceState:
    """
    Asynchronous DSA Expert Node.
    Synthesizes optimal, low-latency algorithmic structures utilizing the local code model.
    """
    logger.info("Initializing DSA algorithm synthesis node execution loop...")
    
    # Retrieve structural parameter context from graph state memory
    payload = state.get("parsed_payload")
    target_lang = state.get("target_programming_language", "Java")
    
    if not payload:
        logger.warning("Empty payload structure passed to DSA expert node. Aborting execution mapping.")
        state["candidate_solution_draft"] = "// Error: Missing problem statement context payload."
        return state

    # Format incoming payload fields into a clean string representation
    problem_data_string = (
        f"Problem Statement: {payload.problem_statement}\n"
        f"Constraints: {payload.constraints if payload.constraints else 'None specified'}\n"
        f"Sample Cases: {payload.sample_cases if payload.sample_cases else 'None provided'}"
    )

    # Dispatch compiled prompt token string to the local asynchronous inference client
    generated_code_response = await inference_driver.generate_completion(
        system_prompt=DSA_EXPERT_PROMPT,
        user_prompt=problem_data_string
    )

    if generated_code_response:
        logger.info("Optimal code structures successfully generated by local inference core.")
        # Store draft solution string into memory layer for self-critic analysis evaluation
        state["candidate_solution_draft"] = generated_code_response
    else:
        logger.error("Local code generation driver returned an empty or invalid execution token block.")
        state["candidate_solution_draft"] = "// Infrastructure Error: Local model generation failure or timeout."

    return state